- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Stop systemd-resolved (conflicts with dnsmasq on port 53)
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Configure dnsmasq for Consul DNS
  copy:
    dest: /etc/dnsmasq.d/10-consul
    content: |
      server=/consul/127.0.0.1#8600
      listen-address=127.0.0.1
      bind-interfaces
    mode: '0644'
  notify: Restart dnsmasq

- name: Remove resolv.conf symlink
  file:
    path: /etc/resolv.conf
    state: absent

- name: Create resolv.conf for dnsmasq
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 127.0.0.1
      nameserver 8.8.8.8
    mode: '0644'

- name: Start dnsmasq
  systemd:
    name: dnsmasq
    state: started
    enabled: yes

- name: Copy nginx load balancer config (HTTP + ACME)
  template:
    src: nginx_lb_http.conf.j2
    dest: /etc/nginx/sites-available/load_balancer.conf
    mode: '0644'
  notify: Restart nginx

- name: Enable nginx load balancer site
  file:
    src: /etc/nginx/sites-available/load_balancer.conf
    dest: /etc/nginx/sites-enabled/load_balancer.conf
    state: link
  notify: Restart nginx

- name: Disable default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Ensure nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- import_tasks: tls.yml

- name: Register nginx service in Consul
  template:
    src: nginx-service.json.j2
    dest: "{{ consul_config_dir }}/nginx-service.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: '0644'
  notify: Reload consul
