app_repo_url: "https://github.com/INITOPS-TEAM/application.git"
app_branch: "feature/INIT-44-image-upload"
app_dest: "/var/www/app"
uploads_path: "/var/lib/pictapp/uploads"
python_requirements: "{{ app_dest }}/app/requirements.txt"